name: 钉钉机器人消息发送
description: 钉钉机器人消息发送

branding:
  icon: 'message-square'
  color: 'green'

inputs:
  token:
    description: '机器人令牌'
    required: true
  status:
    description: '执行状态(-1 启动 0 成功 1 失败)'
    required: true
    default: -1

runs:
  using: composite
  steps:
    - name: Sending Dingtalk Robot Message
      uses: wow-actions/dingtalk-notify@v1
      with:
        token: ${{ inputs.token }}
        msgtype: 'actionCard'
        content: |
          {
            "actionCard": {
              "title": "CI任务${{ inputs.status < 0 && '启动' || (inputs.status == 0 && '执行成功' || '执行失败') }}通知",
              "text": "CI任务",
              "btnOrientation": "1",
              "btns": [{
                "title": "查看项目",
                "actionURL": "dingtalk://dingtalkclient/page/link?url=&pc_slide=false"
              },{
                "title": "查看任务",
                "actionURL": "dingtalk://dingtalkclient/page/link?url=&pc_slide=false"
              }]
            },
            "msgtype": "actionCard"
          }
