name: 钉钉机器人消息发送
description: 钉钉机器人消息发送

branding:
  icon: 'message-square'
  color: 'green'

inputs:
  token:
    description: '机器人令牌'
    required: true
  status:
    description: '执行状态(cancelled 取消 started 启动 success 成功 failure 失败)'
    required: true
    default: 'started'

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ env.START_TIME }}" ]; then
          START_TIME=$(date +%s)
          echo "START_TIME=$START_TIME" >> $GITHUB_ENV
        else
          start_time=${{ env.START_TIME }}
          end_time=$(date +%s)
          seconds=$((end_time - start_time))
          extra="  \n耗时: **$[seconds/60]分$[seconds%60]秒**"
          echo "EXTRA=$extra" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Sending Dingtalk Robot Message
      uses: wow-actions/dingtalk-notify@v1
      with:
        token: ${{ inputs.token }}
        msgtype: 'actionCard'
        content: |
          {
              "title": "CI任务${{ inputs.status == 'success' && '执行成功' || (inputs.status == 'cancelled' && '取消' || (inputs.status == 'failure' && '执行失败' || '启动')) }} 通知",
              "text": "**CI任务<font color='${{ inputs.status == 'success' && '#33CC00' || (inputs.status == 'cancelled' && '#D3D3D3' || (inputs.status == 'failure' && '#FF3333' || '#FF9900')) }}'>${{ inputs.status == 'success' && '执行成功' || (inputs.status == 'cancelled' && '取消' || (inputs.status == 'failure' && '执行失败' || '启动')) }}</font>通知**  \n  项目: **${{ github.repository }}**  \n  分支: **${{ github.ref_name }}**  \n  任务名: **${{ github.workflow }}**  \n  任务ID: **${{ github.run_id }}**  \n  执行人: **${{ github.triggering_actor }}**${{ env.EXTRA }}",
              "btnOrientation": "1",
              "btns": [{
                "title": "查看项目",
                "actionURL": "dingtalk://dingtalkclient/page/link?url=https%3A%2F%2Fgithub.com%2F${{ github.repository }}&pc_slide=false"
              },{
                "title": "查看任务",
                "actionURL": "dingtalk://dingtalkclient/page/link?url=https%3A%2F%2Fgithub.com%2F${{ github.repository }}/actions/runs/${{ github.run_id }}&pc_slide=false"
              }]
          }
